### ISSUE TITLE
Not able to load a txt document

### ISSUE THREAD

**Issue by dmitrym0** [thiswillbeyourgithub/wdoc#1]
Trying to test this locally.

Python 3.12.

I added the following to requirements:

```
dill
youtube_dl
goose3
pdftotext
langdetect
```

I also had to change langdetect imports:

from 
    `from ftlangdetect import detect as language_detect`
to 
    `from langdetect import detect as language_detect`

```
❯ python ./DoctoolsLLM.py --task="query" --path="90-days.txt" --filetype="infer"
 ____            _____           _     _     _     __  __
|  _ \  ___   __|_   _|__   ___ | |___| |   | |   |  \/  |
| | | |/ _ \ / __|| |/ _ \ / _ \| / __| |   | |   | |\/| |
| |_| | (_) | (__ | | (_) | (_) | \__ \ |___| |___| |  | |
|____/ \___/ \___||_|\___/ \___/|_|___/_____|_____|_|  |_|


Hashing files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 214.54doc/s]
Deduplicating files
Loading txt: '90-days.txt'
Error when loading doc with filetype txt: 'string indices must be integers, not 'str''. Arguments: () ; {'task': 'query', 'debug': False, 'path': '90-days.txt', 'filetype': 'txt', 'file_hash': 'b114c1a8b1994861991f'}
Loading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.29doc/s]
Number of failed documents: 1
Traceback (most recent call last):
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/./DoctoolsLLM.py", line 1646, in <module>
    instance = fire.Fire(DocToolsLLM)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/./DoctoolsLLM.py", line 698, in __init__
    self.loaded_docs = load_doc(
                       ^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/utils/file_loader.py", line 262, in load_doc
    assert docs, "No documents were succesfully loaded!"
           ^^^^
AssertionError: No documents were succesfully loaded!
```

**Comment by thiswillbeyourgithub** [comment]
Thanks for giving it a try!

You're among the first external users so it's the kind of stupid issues that are easy to fix :)

I added the missing requirements. Thought langdetect and ftlangdetect IIRC are supposed to be the same but I had troubles installing it (as well as pdftotext) on windows so I made them optional.

To get the full trace output you should add "--debug" : making the fileloading error raise to the cli.

I modified the code quite a bit in the last few weeks so the dev branch will usually have the latest fix earlier than main

**Comment by dmitrym0** [comment]
Thanks for putting it out! I'm excited to try it.

I'm still having an issue with ftlangdetect. Trying this on `dev`. Does python version matter?

```
❯ python ./DoctoolsLLM.py --task="query" --path="90-days.txt" --filetype="infer" --debug
Couldn't import ftlangdetect: 'No module named 'ftlangdetect''
 ____            _____           _     _     _     __  __
|  _ \  ___   __|_   _|__   ___ | |___| |   | |   |  \/  |
| | | |/ _ \ / __|| |/ _ \ / _ \| / __| |   | |   | |\/| |
| |_| | (_) | (__ | | (_) | (_) | \__ \ |___| |___| |  | |
|____/ \___/ \___||_|\___/ \___/|_|___/_____|_____|_|  |_|


Loading model via litellm
Found unexpected keys in doc kwargs: '{'file_loader_n_jobs'}'
Hashing files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 192.67doc/s]
Deduplicating files
Error when loading doc with filetype txt: 'string indices must be integers, not 'str''. Arguments: () ; {'task': 'query', 'debug': True, 'path': '90-days.txt', 'filetype': 'txt', 'file_hash': 'b114c1a8b1994861991f'}
Loading:   0%|                                                                                                                                                                                          | 0/1 [00:00<?, ?doc/s]Traceback (most recent call last):
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/./DoctoolsLLM.py", line 1786, in <module>
    instance = fire.Fire(DocToolsLLM)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/./DoctoolsLLM.py", line 703, in __init__
    self.loaded_docs = batch_load_doc(
                       ^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/utils/batch_file_loader.py", line 260, in batch_load_doc
    doc_lists = Parallel(
                ^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/utils/batch_file_loader.py", line 249, in load_one_doc_wrapped
    return load_one_doc(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/utils/loaders.py", line 230, in load_one_doc
    check_docs_tkn_length(docs, filetype)
  File "/Users/dmitrymarkushevich/workspace/github/DocToolsLLM/utils/loaders.py", line 365, in check_docs_tkn_length
    prob = [language_detect(docs[0].page_content.replace("\n", "<br>"))["score"]]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
Loading:   0%|                                                                                                                                                                                          | 0/1 [00:00<?, ?doc/s]
```

**Comment by thiswillbeyourgithub** [comment]
I don't think python version should matter. I'm on python 3.9.19 though.

I checked and it's because langdetect does not work the same as ftlangdetect. I suggest uninstalling both, or installing only ftlangdetect.

I'll push a fix tomorow I'm late rn

**Comment by thiswillbeyourgithub** [comment]
Hello again, I made many changes today. That include the fix for langdetect. I also changed the installation script etc.

It would be of great help to me if you could reinstall doctoolsllm from scratch and report any issues. Most bugs should be easy to fix and some of them are hard to find without external use!

Edit: refer to the README to see the new way to install DocToolsLLM. Also I'm only talking about the dev branch and will merge depending on your input

Edit2: I also switched to python 3.11.7

**Comment by thiswillbeyourgithub** [comment]
Yeah I updated a ton today too so I'll close this. Please don't hesitate to create issues as it's my only way to catch bugs!

I much improved the README if you want to know more.

**Comment by dmitrym0** [comment]
Ok, I installed the new version per the instructions;

```
❯ python -m pip install git+https://github.com/thiswillbeyourgithub/DocToolsLLM.git@dev
```

I see it installed locally:

```
workspace/github/llmquery via 🐍 v3.12.3 (venv) via 💎 v2.7.8
❯ find .|grep -i doctoolsllm
./venv/bin/doctoolsllm
./venv/lib/python3.12/site-packages/DocToolsLLM-0.16.dist-info
```

However when I execute it, I get an error that the module is not found:

```
workspace/github/llmquery via 🐍 v3.12.3 (venv) via 💎 v2.7.8
❯ python -m DocToolsLLM --task "query" --path "test.pdf" --filetype="pdf"
/Users/dmitrymarkushevich/workspace/github/llmquery/venv/bin/python: No module named DocToolsLLM
```

any idea what it's about?

**Comment by thiswillbeyourgithub** [comment]
Oh shoot I think I only tested the install in the cloned folder. I'll fix that tomorow but in the meantime try to git clone then `install .`

Sorry and thanks!

**Comment by thiswillbeyourgithub** [comment]
Should be fixed now. I got stuck in seemingly non deterministic bugs that were extra annoying. Though now for some reason the logs are printed in doubles on my computer. I'll keep improving it anyway.

Regarding the way to run DocToolsLLM, 3 possibilities:
1. DocToolsLLM directly in your console
2. python -m DocToolsLLM
3. clone the repo, then checkout dev, then PYTHONPATH="." python -m DocToolsLLM should do the trick
